spring.application.name=order-processing-orders

jwt.secret=${JWT_SECRET}

# disabling; REST services only here
spring.jpa.open-in-view=false

# orders props
com.orderprocessing.orders.page-size=50
com.orderprocessing.orders.max-page-size=50
com.orderprocessing.orders.products-default-sorting-attribute=name
com.orderprocessing.orders.query-batch-size=100
com.orderprocessing.orders.query-max-size=1000

shipments.service.url=http://localhost:8082/shipments
enable.feign.notifications=true

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
