spring.application.name=order-processing-orders

jwt.secret=${JWT_SECRET}

# disabling; REST services only here
spring.jpa.open-in-view=false

# orders props
orders.demo.orders.page-size=50
orders.demo.orders.max-page-size=50
orders.demo.orders.products-default-sorting-attribute=name
orders.demo.orders.query-batch-size=100
orders.demo.orders.query-max-size=1000

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
