spring.application.name=order-processing-orders

jwt.secret=${JWT_SECRET}

# disabling; REST services only here
spring.jpa.open-in-view=false

server.servlet.context-path=/orders

# orders props
com.orderprocessing.orders.page-size=50
com.orderprocessing.orders.max-page-size=50
com.orderprocessing.orders.products-default-sorting-attribute=name
com.orderprocessing.orders.query-batch-size=100
com.orderprocessing.orders.query-max-size=1000

# OpenAPI
openapi.title=Orders API
openapi.version=v2

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when-authorized
management.endpoint.loggers.access=unrestricted

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

logging.level.org.springframework.boot.autoconfigure.security=WARN
